apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trifid
  annotations:
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: ld-data-bs-ch.zazuko.net,ld-data-bs-ch.zazukoians.org
spec:
  tls:
    - secretName: ld-data-bs-ch-cert
      hosts:
        - ld.data-bs.ch
  rules:
    - host: ld.data-bs.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trifid
                port:
                  number: 80
