apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ld-data-bs-ch

commonLabels:
  app.kubernetes.io/instance: ld.data-bs.ch
  app.kubernetes.io/name: trifid

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
